### ISSUE TITLE
drag_start vs dragstart

### ISSUE THREAD

**Issue by StellarCodeOrg** [pyjun01/react-google-map-wrapper#3]
I just noticed a small typo in the event handlers for Advanced Markers: I think somewhere in the code, "drag_start" should be replaced by "dragstart". ("dragend" works perfectly though!). 
https://developers.google.com/maps/documentation/javascript/reference/advanced-markers
Great work by the way!

**Comment by pyjun01** [comment]
Thank you for your reporting! It's fixed in v1.0.6 👍
